### ISSUE TITLE
Handle 'null' for emty-to-many relationships

### ISSUE THREAD

**Issue by victorgambert** [mrichar1/jsonapi-vuex#102]
My JSON API send me a ressource with a empty relation like the example above

```
...
relationships: {
   comment: {
      data: null
   }
}
```

Like the JSONAPI spécification say [here](https://jsonapi.org/format/#document-resource-object-linkage) ressource linkage MUST be represent by 'null' for empty-to-one relationships.

When this happen, jsonapi-vuex send an error as following "TypeError: "right-hand side of 'in' should be an object, got null"

**Comment by mrichar1** [comment]
Hi, Thanks for flagging this up.

I can see a couple of places where the code won't correctly handle `null` which I'm currently looking to fix.

I can't immediately replicate your bug (though I believe it does exist - it's just that the test suite doesn't cover it. Can you let me know which vuex action/getter etc you are calling to make this error appear? Thanks!

**Comment by victorgambert** [comment]
Hi Matthew, thank you for you quick reply,

To help you replicate the bug, I use the getRelated method action/getter like specify in the documentation : 

`store.dispatch('jv/getRelated', 'relation/id')`

Thank you for you work, this package is awesome !

Victor

**Comment by mrichar1** [comment]
Thanks for the detail of where you were seeing the bug - this allowed me to reproduce it, and I've added a test and (hopefully!) fixed the code as a result.

If you can test the update (see the PR comments) and let me know if it solves your problem that'd be great!

**Comment by mrichar1** [comment]
Fix available in release `3.2.0`
