### ISSUE TITLE
What if you need to add extra actions / mutations or getters to your store?

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#105]
This is more of a question – or an enhancement request...

I have a requirement where I want to adjust the logic for the actions so that they look first in indexedDB before hitting axios. I'm looking for a way to add that in. There might also arise the odd requirement for custom mutations or getters (e.g. concat firstname and lastname).

One solution I can think of for actions is to use middleware for axios which can check indexedDB for data first. That's fine, but what about getters and mutators?

Is there a way to manually create the module and just implement and override jsonapiModule? Some boilerplate to that effect would be grand.

**Comment by geoidesic** [comment]
I came up with this boilerplate for the module `index.js`:
```
import state from "./state";
import * as getters from "./getters";
import * as mutations from "./mutations";
import * as actions from "./actions";
import { jsonapiModule } from "jsonapi-vuex";
import { config } from "src/boot/axios";
import axios from "axios";
import _ from "lodash";

const api = axios.create(
  _.merge({}, config, { baseURL: config.baseURL + "/users" })
);
const jvModule = jsonapiModule(api);
jvModule["mutations"] = _.merge(jvModule["mutations"], mutations);
jvModule["getters"] = _.merge(jvModule["getters"], getters);
jvModule["actions"] = _.merge(jvModule["actions"], actions);
jvModule["state"] = _.merge(jvModule["state"], state);

export default {
  namespaced: true,
  ...jvModule
};

```

**Comment by geoidesic** [comment]
Seems to work.

**Comment by mrichar1** [comment]
Hi - thanks for asking the question!

Yes, all of `actions`, `getters` and `mutations` are simply objects which can be modified.

I'd avoid the complexity of using `_.merge` unless you have a specific situation where you are overriding existing items in a complex way. The simplest solution is to just do a shallow merge using `Object.assign`, e.g.:
```
Object.assign(jvModule["mutations"], mutations)
```
