### ISSUE TITLE
Why does each request accumulate _jv records in the store (or why doesn't status work)?

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#114]
Each time a request is made I end up with an extra record under the `_jv` node in the store. E.g.:
<img width="386" alt="Screenshot 2019-11-23 at 18 55 50" src="https://user-images.githubusercontent.com/4637995/69482383-152aeb80-0e23-11ea-9685-155cd618d020.png">

Some questions:
1. I'm concerned that this might represent a memory leak?
2. If I'm interested in the status and timestamp of a request, how do I know which of these records to reference?
3. The docs say that the response will contain the id of the request... but I'm always only ever seeing id = 1 in the response, which is the id in my persistence layer, i.e. that returned by the back-end api. I'm not seeing a response id which correlates to these request ids.
4. status as described here: https://github.com/mrichar1/jsonapi-vuex#status doesn't seem to work. It just shows as `undefined` if I do the console.log(status).

Here's what my response object looks like as returned by the _jv action as an async:
<img width="327" alt="Screenshot 2019-11-23 at 19 09 01" src="https://user-images.githubusercontent.com/4637995/69482492-c716e780-0e24-11ea-9a42-77259f6e3867.png">

Here's what it looks like as a promise:
<img width="429" alt="Screenshot 2019-11-23 at 19 15 34" src="https://user-images.githubusercontent.com/4637995/69482559-b1ee8880-0e25-11ea-8417-18fa40cdbb27.png">

**Comment by mrichar1** [comment]
The status code is designed in a way that can't be guarenteed to work with how Vuex handles action promises. It will be being rewritten, but this hasn't happened yet.

Closing this in favour of #75
