### ISSUE TITLE
clearRecords mutation doesn't seem to work?

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#115]
I do a `store.dispatch('clients/get')` followed by a `console.log(store.getters['clients/get']()` I can see that the records have been fetched and stored to Vuex correctly. If I then do `store.commit('clients/clearRecords')` I get the following errors and the store is not cleared:
<img width="557" alt="Screenshot 2019-11-24 at 14 25 11" src="https://user-images.githubusercontent.com/4637995/69494591-3ee91e80-0ec6-11ea-9f5e-f7e5d7e4956c.png">

My store looks like this:
<img width="165" alt="Screenshot 2019-11-24 at 14 29 24" src="https://user-images.githubusercontent.com/4637995/69494648-dcdce900-0ec6-11ea-8179-d479c49eac87.png">

I also tried this:
```
store.commit('clients/clearRecords', 'clients')
```
and this
```
store.commit('clients/clearRecords', 'users')
```
and this (which doesn't cause an error but also doesn't clear the store)
```
store.commit('clients/clearRecords', store.getters['clients/get']())
```
Looking at the code for `clearRecords` it looks broken to me because the comments say that the `records` parameter can be a string but the first thing that happens is that `records` is processed by `normToStore`, which (according to its comments) can only accept an object, not a string.

**Comment by mrichar1** [comment]
You're right that the documentation is incorrect -  it looks like the docs for the *Records mutations were copied from `deleteRecords (which does take a string) but not modified. I'll update the docs to reflect this mistake.

So for now you need to do:

`store.commit('clearRecords', { _jv: { type: 'clients' } })
