### ISSUE TITLE
Keys with snake-case are converted to kebab-case

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#116]
I'm storing a set of nested key-value pairs (some of the key's values are json objects). It's being processed by the back-end correctly but when reading data from the back-end the response shows keys that were kebab-case as snake-case.

E.g. I have a key `client_table`. That's how it looks in my due component's data model. When I save it it saves to a MySQL table column by the same name. However, when I fetch the object from the back-end via jsonapi-vuex it is saved to the Vuex store as `client-table`.

I'm confused by this behaviour. How am I to load data saved to the store in this fashion back into the component's data model?

So for example:
```
data(): {
  form: {
    enquiry: {
      client_table: 'persons'
    }
  }
}
```
In my component's template I have markup that refers to `enquiry.client_table`.
When I load the record via jsonapi-vuex and then do something like: 
```
load() {
   this.$store
  .dispatch('jv/get', ['enquiry/1', { params: params }])
  .then((data) => {
    this.$set(this.form, "enquiry", data)
  })
}
```
I get errors because the key that exists in data is `client-table` not `client_table`.

It seems really strange and unnecessary to me that this conversion is happening. Kebab-case isn't favoured by JSON nor JavaScript. (You can't do `enquiry.client-table` for example), so why would snake-case be converted? I assume it's something to do with the JSONAPI spec because my back-end JSONAPI plugin seems to handle it fine and converts it all back to snake-case when writing to the database. However I don't understand how it would know what to do if I mixed snake-case and kebab-case if it is performing conversions.

**Comment by mrichar1** [comment]
`jsonapi-vuex` shouldn't be doing any case modification on data coming from the API - it's just storing it 'as-is'.

Can you confirm that the issue is not that the API is modifying the data, using a different tool to POST/GET, such as `https://httpie.org/`

Additionally, I'm not sure why you are using `this.$set` to try to push the response from the API into component `data`, when the usual route is to use computed properties and/or Vuex getters to access the saved results from the store?

**Comment by geoidesic** [comment]
You're right, it is the backend API. I'm using `friendsofcake/crud-json-api` on the backend. I managed to fix this with config.

The reason I'm using this.$set is simply because the form in question was developed before vuex was added to the system, so it has a data structure in place which I haven't yet refactored. But that shouldn't be material to the issue in question I don't think.

**Comment by geoidesic** [comment]
I still seem to be doing something wrong though, so perhaps it is material after all. When I try to set my model I get this error:
```
TypeError: Cannot read property 'includes' of undefined
```
Which tells me that the type of the properties being picked up is not correct. The value in question was a javascript array but somehow in the the response I'm getting from jsonapi-vuex it is no longer a JavaScript array?

**Comment by geoidesic** [comment]
Argh... never mind. This is due to my schema having changed and me not updating the front-end code.
