### ISSUE TITLE
[NFR] Nuxt support

### ISSUE THREAD

**Issue by ruudboon** [mrichar1/jsonapi-vuex#13]
Would be great if this (Amazing lib!) adds Nuxt Universal SSR support.

**Comment by mrichar1** [comment]
Hi,

Thanks for the suggestion! I've not used `Nuxt` before, so I'm just going from the docs, but I assume you're referring to what's in the docs here: https://nuxtjs.org/guide/vuex-store#modules-mode

If I'm reading this correctly, I think this could be implemented by doing something like the following.

Create `store/jv.js` containing:

```
import axios from 'axios';
import { jsonapiModule } from 'jsonapi-vuex';

api =  axios.create(...)
const { state, mutations, actions, getters } = jsonapiModule(api)
export { state, mutations, actions, getters }
```
Please try this out and let me know if this works as expected.

**Comment by SamGold05** [comment]
Include plugin in your `nuxt.config.js` file:

`plugins: ['~/plugins/jsonapi-vuex.js']`

And your `plugins/jsonapi-vuex.js` will look like:

```
import { jsonapiModule } from 'jsonapi-vuex'

export default function({ $axios, store }) {
  store.registerModule('jv', jsonapiModule($axios))
}
```

**Comment by alexd73** [comment]
Hi! Both methods give the error Unexpected token export.
How to I can solve this problem?

**Comment by mrichar1** [comment]
Hi - This looks like the module isn't being transpiled properly by Babel.

Assuming you have Nuxt/Babel set up properly, the only thing I've found is a suggestion to do the following, which prevents server-side rendering (which is unsupported):

```
plugins: [
  {src: '~/plugins/jsonapi-vuex', ssr: false},
]
```

Afraid I'm just reading docs here, and not a Nuxt user - so if that doesn't work it might be worth following up with the Nuxt community!

**Comment by SamGold05** [comment]
In `nuxt.config.js` add this:
`
{
    build: {
        transpile: ['jsonapi-vuex']
    }
}
`

**Comment by s1nz** [comment]
Hi @mrichar1! I've successfully added the library and it seems to work fine with my Nuxt setup, but I cannot get any getters to work :( Any ideas?

**Comment by s1nz** [comment]
Hi @mrichar1! I cannot get the status getter to work, there is no `id` in the Promise. Any ideas?

**Comment by samnight** [comment]
Use async function. Action return a promise.

**Comment by s1nz** [comment]
@samnight thanks, but Axios already returns a Promise. Do I miss something?

**Comment by mrichar1** [comment]
@s1nz I'm not sure what might be causing the getter id to be missing from the Promise. Please open a  new issue so that this one can stay focused on Nuxt support issues - thanks!

**Comment by s1nz** [comment]
thanks, @mrichar1, I'll create a new issue.
