### ISSUE TITLE
If get returns empty, the store is not updated

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#133]
E.g. if I truncate a table on the backend, then do a get on that store, the vuex store will not truncate.

I'm also not sure how to manually empty the store in that case.
e.g.
```
[err, response] = await to(store.dispatch(...destructure));
if(empty(response)) {
    // do something here to empty the store manually.
}
```

**Comment by mrichar1** [comment]
There are a couple of options available here.

1. Use the `clearRecords` mutation. It could do with better documentation, but (from memory) I think you can do:

`this.$store.commit('jv/clearRecords', { _jv: { type: 'foo' } }` to delete all records of type `foo`.

2. Set the config option `clearOnUpdate` to `true` - with that set every new response from the API will be treated as the definitive data for that `type` and all other records of that `type` will be deleted.

This is more useful if you are usually dispatching to a collection endpoint - less so if you commonly dispatch for individual items.

Let me know if either of those solves your issue?

**Comment by geoidesic** [comment]
Yeah, no I should have said, `clearOnUpdate` is set to true but it still doesn't work if the result is empty.

**Comment by mrichar1** [comment]
Ah, I see the problem - `clearOnUpdate` causes `clearRecords` to be committed with the returned data as the argument, but if the response is empty there will be no `type` available.

I'll have a think about what should happen here - one option would be to pass the endpoint name instead, but there's no guarantee that this matches the `type`.
I think the best workaround for now is to call `clearRecords` in your code, setting the type explicitly.

**Comment by mrichar1** [comment]
I've made a new release (`4.3.0`) which uses the `endpoint` as the `type` when `clearOnUpdate` is set. Please can you try this out and let me know if that fixes your issue!
