### ISSUE TITLE
Can't mock jvModule['actions']

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#136]
This has been driving me nuts all day. I get this error:
```
 TypeError: Cannot set property fetch of #<Object> which has only a getter
```
I'm using jest and I'm mocking the vuex store in tests. It works fine without `jsonapi-vuex`. It also works fine with mutations... I can modify those... but not actions. Makes no sense.

E.g. my store looks like this:
```
import stateImport from "./state";
import * as getterImport from "./getters";
import * as mutationImport from "./mutations";
import * as actionImport from "./actions";
import { jsonapiModule } from "jsonapi-vuex";
import { config } from "src/boot/axios";
import axios from "axios";
import _ from "lodash";
const api = axios.create(_.merge({}, config, { baseURL: config.baseURL }));
const jvModule = jsonapiModule(api, {
  clearOnUpdate: true
});
export const namespaced = true;
export const state = _.merge(jvModule["state"], stateImport);
export const getters = _.merge(jvModule["getters"], getterImport);
export const mutations = _.merge(jvModule["mutations"], mutationImport);
export const actions = _.merge(jvModule["actions"], actionImport);
```

In my test I then mock the store and some of it's mutations and actions. I can mock the mutations no problem but the minute I try to mock the actions I get that error. Also if I don't use the jvModule['actions'] then it's fine. E.g.
```
export const actions = actionImport;
```
That works.

The way I'm creating the mocked actions and mutations are like so:
```
export const mockStore = args => {
  let store = {};
  if (args.modules) {
    store.modules = {};
    _.each(args.modules, (module, name) => {
      store.modules[name] = mockStoreModule(module);
    });
  } else {
    store = mockStoreModule(module);
  }
  store = new Vuex.Store(store);
  store.commit = jest.fn();
  store.dispatch = jest.fn();
  return store;
};
export const mockStoreModule = storeModule => {
  let actions = _.get(storeModule, "actions");
  if (actions) {
    _.each(actions, (val, key) => {
      storeModule["actions"][key] = jest.fn();  // this causes the error
    });
  }
  let mutations = _.get(storeModule, "mutations");
  if (mutations) {
    _.each(mutations, (val, key) => {
      storeModule["mutations"][key] = jest.fn();   // this works
    });
  }
  return storeModule;
};
```

Any ideas? I really can't see why it should work for mutations but not for actions. I also can't find a workaround that allows me to mock jvModule actions.

**Comment by mrichar1** [comment]
I'm not a user of `jest` but I've had a quick read of the docs and looked at some other people seeing this error, and it seems to be that for some types of mocking `jest` tries to replace the function with it's own by modifying the original function.

The way that babel re-exports ES6 modules means that they only have a getter, and so can't be modified.

There are a number of solutions offered here: https://stackoverflow.com/questions/53162001/typeerror-during-jests-spyon-cannot-set-property-getrequest-of-object-which

I think the one most likely to work is to use `jest.mock` which doesn't do this function-replacement and so shouldn't throw the error.

Let me know if this works, as it's good to build up a collection of these kinds of fixes for real-world uses.
