### ISSUE TITLE
How to update To-Many Relationships?

### ISSUE THREAD

**Issue by pharkasbence** [mrichar1/jsonapi-vuex#138]
How can I send a request like this (https://jsonapi.org/format/#crud-updating-to-many-relationships)?

```
POST /articles/1/relationships/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    { "type": "comments", "id": "123" }
  ]
}
```

**Comment by mrichar1** [comment]
Hi - this is already open as #88 - it's on the todo list! :smiley: I'll close this - feel free to add any extra comments on that issue.
