### ISSUE TITLE
Struggle to access some related / included data

### ISSUE THREAD

**Issue by gizmo84** [mrichar1/jsonapi-vuex#156]
Hi there,

First I want to thank your for your awesome library. We are using it with the quasar framework and it's working pretty fine.

One area witch isn't currently working for me is the access to related or included data. I'm trying to get access to following URL: [https://www.swr.de/api/v1/json/documents/7-tage-kloster-arenberg-100?include=involvedPersonsWithRole](https://www.swr.de/api/v1/json/documents/7-tage-kloster-arenberg-100?include=involvedPersonsWithRole) with following code:

```
this.$store.dispatch('jv/get', `documents/7-tage-kloster-arenberg-100`)
    .then((data) => {
        console.log(data)
    })
    .catch((error) => {
        console.log(error)
    })
```

And than access to included data (for example involvedPersonsWithRole). But the returned object is empty.

Same problem is happening for related data with following code:

```
this.$store.dispatch('jv/getRelated', `documents/7-tage-kloster-arenberg-100/involvedPersonsWithRole`)
    .then((data) => {
        console.log(data)
    })
    .catch((error) => {
        console.log(error)
    })
})
```

But the returned object is empty too.

I'm not sure if the problem is coming from the library or from the api and need a little bit help to debug it :)

**Comment by mrichar1** [comment]
Hi - thanks for letting us know this library is useful to you!

Can I check that you are passing the `include` parameter to the API request? I'd expect something like the following to work:

```
let params = { include: 'involvedPersonsWithRole' }
this.$store.dispatch('jv/get', [`documents/7-tage-kloster-arenberg-100`, { params: params }])
```

**Comment by mrichar1** [comment]
Right - yes it should work just as well done globally like that.

The `include` data should be added to the store under the 'type' key - i.e. `involvedPersonsWithRole`.

You should be able to access this using the 'get' getter:

```
this.$store.getters['jv/get']('involvedPersonsWithRole/7+tage+kloster+arenberg+100+involvedPersonsWithRole+1')
```

Or if you are accessing `state` directly, using the square braces object notation:

```
this.$store.state.involvedPersonsWithRole['7+tage+kloster+arenberg+100+involvedPersonsWithRole+1']
```

I'm not sure why `getRelated` is returning an empty object though... I'll see about setting up a test app to point to this API and try debugging it myself.

**Comment by mrichar1** [comment]
OK, the issue with `getRelated` seems to be a problem with the API, not the code...

According to the JSONAPI spec, the server MUST support accessing a resource's relationships in the form of `/collection/item/relationship_name`, e.g. `/articles/1/author` : https://jsonapi.org/format/#fetching-resources

`jsonapi-vuex` relies on this and simply passes the string through as the url, so:

```
this.$store.dispatch('jv/getRelated', `documents/7-tage-kloster-arenberg-100/involvedPersonsWithRole`)

// Fetches

https://www.swr.de/api/v1/json/documents/7-tage-kloster-arenberg-100/involvedPersonsWithRole
```

The server returns HTTP code `200` but then includes a text body that says `HTTP Status 400` - which is obviously broken.

If you're unable to get the API owners to fix this to match the JSONAPI spec, then the fallback is just to use `getRelated` without the 3rd argument in the path, and then manually extract it later.

**Comment by gizmo84** [comment]
@mrichar1 Big Thanks for your help. I will try to contact the API owners. I think I can close this issue! ;)
