### ISSUE TITLE
Using href url

### ISSUE THREAD

**Issue by mrichar1** [mrichar1/jsonapi-vuex#159]
Hello, @mrichar1 

I am new guy for this package and I'd like to use this one for my project.
So I have one issue and want your help.

I've got the json api like this.
baseUrl : https://dev-54ta5gq-2mtjdsd3z4gog.de-2.platformsh.site/jsonapi
method: Get,
its response looks like following

```
{
    "jsonapi": {
        "version": "1.0",
        "meta": {
            "links": {
                "self": {
                    "href": "http://jsonapi.org/format/1.0/"
                }
            }
        }
    },
    "data": [],
    "links": {
        "action--action": {
            "href": "https://dev-54ta5gq-2mtjdsd3z4gog.de-2.platformsh.site/jsonapi/action/action"
        },
        "api_key--api_key": {
            "href": "https://dev-54ta5gq-2mtjdsd3z4gog.de-2.platformsh.site/jsonapi/api_key/api_key"
        },
        "base_field_override--base_field_override": {
            "href": "https://dev-54ta5gq-2mtjdsd3z4gog.de-2.platformsh.site/jsonapi/base_field_override/base_field_override"
        }
    }
}
```

I want to get the data from the href url related to the specific links key.
But I don't know how to do this.
Can you give me advice?
Thanks.

_Originally posted by @hakuna0829 in https://github.com/mrichar1/jsonapi-vuex/issues/158#issuecomment-717417140_

**Comment by mrichar1** [comment]
Hi - I've moved this into a new issue to avoid complicating the original one.

Collection `links` aren't kept by default, since these may change with the request - and in this case since there is no `data` nothing will be added to the store.

You can ask for the original JSON to be added to the response, in which case it will be kept in `_jv.json`

You can enable this by setting the `preserveJson` configuration option when setting up the module:

```
jm = jsonapiModule(api, { preserveJson: true })
```

You can then access the links from the resulting response, for example:

```
this.$store.dispatch('jv/get', 'jsonapi').then((data) => {
  console.log(data._jv['json']['links']['action--action']['href']
})
```

I don't know the full extent of your API or project, but I would add that if the JSONAPI you are getting back only ever contains `links` and `data` is always empty, then using this library might be overkill, since the store will always be empty. In that case just making 'direct' API requests and processing the `links` out of the response might be simpler.

**Comment by hakuna0829** [comment]
Hi, @mrichar1 
Thanks for your quick guide.
I think it's good solution, but getting errors.
Maybe I didn't write its logic in my code.
Here are details.

```
//service/api.js
import axios from 'axios';

export default () => (axios.create({
  baseURL: 'https://dev-54ta5gq-2mtjdsd3z4gog.de-2.platformsh.site/jsonapi/',
  withCredentials: false,
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/vnd.api+json',
  },
}));

//store/index.js
import API from '../service/api';

export default new Vuex.Store({
  state: {
  },
  mutations: {
  },
  actions: {
  },
  modules: {
    jv: jsonapiModule(API),
    jm: jsonapiModule(API, { preserveJson: true }),
  },
});

//Home.vue

export default {
  name: 'Home',
  async mounted() {  
    this.$store.dispatch('jm/get', 'jsonapi').then((data) => {
      console.log('jm data', data);
    });
  },
};
```

Error on browser console.
http://prntscr.com/vaaycp

Let me know what I did mistake after checking above.
Thanks.

**Comment by mrichar1** [comment]
I think you want to set `baseURL: 'https://dev-54ta5gq-2mtjdsd3z4gog.de-2.platformsh.site` since by having it include `/jsonapi` the dispatch is trying to get `/jsonapi/jsonapi`

You can confirm this by adding error-handling to your code - i.e.:

```
async mounted() {  
    this.$store.dispatch('jm/get', 'jsonapi')
      .then((data) => {
        console.log('jm data', data);
      })
      .catch((errs) => {
        if (errs.response) {
          // axiom error
          console.log('HTTP Error Code:', errs.response.status)
          console.log('Error:', errs.response.data)
        } else {
          // Some other type of error
          console.log(errors.message)
        }
      })
```
