### ISSUE TITLE
How to normalize keys from server

### ISSUE THREAD

**Issue by cloke** [mrichar1/jsonapi-vuex#179]
First I want to say I super appreciate this library.

Is there a proper approach to converting keys from the server? The json api response uses kebab case, but we'd like the Vuex store to keep them as camelCase. Then when we save a record they'd be transformed back. 

I thought `utils. jsonapiToNorm` might do the trick, but it is unclear how to modify the data before jsonapi-vuex puts it into the store. I have the code to actually recursively change the keys, just need to know where to put it.

**Comment by mrichar1** [comment]
This isn't something the code currently has support for - I'm not 100% sure there is a 'single point' in the code where you could put in translation and guarantee that it would apply everywhere. At the very least it would need to be in `jsonapiToNorm`/`normToJsonapi` but possibly also in `getURL` and some of the relationship handling code.

Perhaps the easiest option is to do this with the request/response using `axios` interceptors: https://github.com/axios/axios#interceptors

There's a middleware module that does this between camel and snake case that might work 'as-is' or serve as inspiration fotr your own translation layer: https://www.npmjs.com/package/axios-case-converter

Let me know if that would be enough to do what you need - I'd be happy to look at adding hooks into the `utils` functions, but it might not be necessary if the above works!

**Comment by cloke** [comment]
That works. Thank you.
