### ISSUE TITLE
Track loading state

### ISSUE THREAD

**Issue by mhluska** [mrichar1/jsonapi-vuex#18]
One thing I miss after moving away from reststate-vuex is [automatic tracking of loading state](https://github.com/reststate/reststate-vuex/blob/fb1ccd2e3df86b1e1d58a352d6c829959ba69d42/src/vuex-jsonapi.js#L100).

It would be a nice feature to add to remove some boilerplate around adding loading indicators to the UI.

**Comment by mrichar1** [comment]
Hi - thanks for requesting this feature!

I've had a look at the other project, and while I can see at a high-level what this is doing, I have some concerns with how it is implemented.

Since all `actions` are asynchronous (`axios` api requests) any number can be in-flight at once, and if they are all attempting to manipulate a single `status` then they will be constantly overwriting each other, and not providing any meaningful information (unless I'm missing something?)

I can imagine potentially tracking each `action` with it's own id, and then storing the state of each action - though there are some interesting challenges in returning an id synchronously to track an asynchronous promise.

**Comment by mrichar1** [comment]
OK - so with a bit of digging, this could be achievable - might need to sleep on it to see if any gotchas pop up though before implementing anything...

1. Create `state._jv.status = {}` to hold `action ids`
2. Create a `sequence` generator to generate unique ids.
3. When called, each action gets the next `id` from the generator - guaranteed to be unique.
4.  The `id` is attached to the promise as a property (`_jv_id`) which is immeidately accessible by the `action` caller.
5. The action updates `state._jv.status.id` as it progresses (INIT, LOADING, SUCCESS, ERROR).

So if you need to track the state, you do something like:

```
// Get the promise object from the action dispatch
let action = this.$store.dispatch('jv/get', "widget")

// Track the action state
let state = state._jv.status[action._jv_id]

// Handle the promise resolution/rejection as normal
action.then( result => {
  ...
})
```
Use is unchanged if you don't care about the state.

Does that seem to match the kind of situation you'd want to use it in? (`state` variable can be used in the UI to toggle loading/success hinting etc).

**Comment by mhluska** [comment]
Totally agreed on the multiple in-flight requests overriding the loading state.

That solution seems fine to me. The only suggestion I would make is it would be nice if the use of IDs was hidden from the user of the library. Maybe a function: `let state = state._jv.status(action)`?

The abstraction I'm used to in the Ember world is a [Task in Ember Concurrency](http://ember-concurrency.com/docs/introduction/). Though I'm new to Vue and not sure how cleanly that translates over.

**Comment by mrichar1** [comment]
Glad that solution suits you. The Ember Task abstraction seems like a good approach, at least as far as promise states are concerned. If I was to implement anything more 'serious' then I'd probably consider using rxjs Observables or similar to leverage a lot more functionality, but that's outside the scope for now!

I'll look at implementing functions to abstract away some of the getting and querying the status and hiding ids.

There are also some other potential helper functions that could exist - such as ones for garbage collection, total counts for in-flight, successes, errors etc, request timeout checking, etc - though I don't now how useful each of these might be. I'll get the basics implemented, and then see what extra features might be useful.

**Comment by mrichar1** [comment]
I've pushed a `status` branch containing the changes I think are needed to implement this - the easiest way to review the changes is via the 'compare' interface in github:

https://github.com/mrichar1/jsonapi-vuex/compare/status

Have a look at the docs (and the underlying implementation if you fancy it!) and let me know if that looks good to you.

I need to do some more work to add in garbage collection, so if there are any other helper methods (like the `status` getter you think would be useful, please let us know.

**Comment by mhluska** [comment]
Thanks for getting to this so fast! I will give it a try now.

**Comment by mrichar1** [comment]
I've done some more work on the `status` branch (fixed getRelated, added expiry of old status records and added tests) so I think this is now pretty much 'ready to go'.  Let me know if you get a chance to test it - either way I'll probably push this into `master` and release a new version in the next week or so.

**Comment by mhluska** [comment]
I gave it a quick test and it seems to be working ok for me. Thank you 👍

**Comment by CodingItWrong** [comment]
@mrichar1 @mhluska Hey y'all, I'm the maintainer of reststate/vuex—I just found this thread via a random search. @mrichar1 I think I remember us talking briefly early in the life of both projects. @mhluska I'm glad this library is meeting your needs better! And glad we're all experimenting in this space 👍
