### ISSUE TITLE
Should Throw Error for 4xx, 5xx etc

### ISSUE THREAD

**Issue by mhluska** [mrichar1/jsonapi-vuex#21]
It looks like this library uses this pattern frequently:

```js
.catch((error) => {
  return error
})
```

This makes it impossible to use something like this in Vue:

```js
async beforeRouteEnter(to, from, next) {
  try {
    await store.dispatch('jv/get', `users/${username}`);
  } catch (error) {
    // TODO: Handle 404 here.
  }
},
```

As a workaround, I have to check if the passed value is an Error object:

```js
const response = await store.dispatch('jv/get', `users/${username}`);

if (response instanceof Error) {
  // TODO: Handle 404 here. 
}
```

I think a solution might be to just remove the `.catch()` in the library to prevent swallowing errors. Or have the library check the status code to decide if it should catch the error or not.

**Comment by mrichar1** [comment]
Yes, you're quite right - this stems from planning in the past to implement some optional error-handling/throwing code, which I never got round to (and forgot to make a note to this effect!).

With the new `status` branch it still needs to catch the error to update the status record- however it should then be a config option as to whether to log and return, or throw - depending on whether the module user wants errors to be fatal or not.

I'll see about implementing this in the near future.

**Comment by mrichar1** [comment]
Implemented in the `status` branch (just replaced returns with throws) and will close this call when that branch is merged into `master`.
