### ISSUE TITLE
Integration with vuex-orm?

### ISSUE THREAD

**Issue by mhluska** [mrichar1/jsonapi-vuex#24]
I'm starting to rely on this library more heavily and I'm starting to have a need for computed properties on models. For example, a formatted price computed property on an item model.

I'm wondering if there is an easy way to integrate this with something like [vuex-orm](https://github.com/vuex-orm/vuex-orm). Coming from Ember, I'm used to having this JSON:API and ORM layer working out of the box.

It seems like if I use this library to fetch data and then manually re-insert it using vuex-orm, I'll end up with two copies in the store.

It looks like they have various plugins like [Vuex ORM Axios](https://github.com/vuex-orm/plugin-axios) so maybe this feature should exist as a plugin over there?

An alternate idea would be for this library to provide a hook which can override the mechanism that puts data into the store. That would allow integration with vuex-orm. Not sure if this is a bad idea though.

Edit: I realized I can hook into the mutation from this library like so:

```js
new Vuex.Store({
  mutations: {
    'jv/add_records'(state, records) {
      console.log(state, records);
    },
})
```

But I don't think this overrides the original mutation from this library.

**Comment by mrichar1** [comment]
I'll consider this one more properly later - however for now, it should be easy to override a particular mutation, since everything comes back as nested objects. Something like the following should work:

```
const jvModule = jsonapiModule(api)
jvModule['mutations']['add_record'] = (state, records) => { // New mutation code }

export default new Vuex.Store({
  modules: {
    'jv': jvModule
  }
});
```
