### ISSUE TITLE
Dispatch API without array args

### ISSUE THREAD

**Issue by mhluska** [mrichar1/jsonapi-vuex#30]
Currently, it seems we have to pass an array to call dispatch with query params:

```js
this.$store.dispatch('jv/get', ['widget/1', {params: params}]);
```

It would be slightly nicer if we could just call it like so:

```js
this.$store.dispatch('jv/get', 'widget/1', { params: params });
```

Is there anything blocking us from modifying the API to receive non-array args?

**Comment by mrichar1** [comment]
Unfortunately `dispatch` can only ever take 3 parameters: the  action`, it's argument s, and a namespace root parameter: 

https://vuex.vuejs.org/guide/modules.html#accessing-global-assets-in-namespaced-modules

We allow the action args to not be an array if no `params` option is passed, but have to use an array for multiple args.

(We could instead use an object, but I didn't see a need for keyed args here).

**Comment by mhluska** [comment]
Ah you're right. #vuenoob
