### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by SamGold05** [mrichar1/jsonapi-vuex#39]
Hi!
Update please npm version to the latest.

**Comment by mrichar1** [comment]
Apologies - the code has been changing rapidly so I forgot regular releases!

I've released 0.1.2 which includes a lot of fixes, but no major implementation changes. There are a number of other code changes going through just now (which make major changes to the code and usage) so a new (minor or major) release bump will be happening soon!

**Comment by mrichar1** [comment]
The easiest option was to just release the first of the big changes as [`0.2.0`](https://www.npmjs.com/package/jsonapi-vuex/v/0.2.0). Main changes are:

* config options are now in `camelCase` - e.g. `follow_relationships` -> `followRelationships`
* `followRelationships` is now recursive.

(Plus lots of bug fixes/behind-the-scenes restructuring).
