### ISSUE TITLE
Getter for relationships?

### ISSUE THREAD

**Issue by stefanvanherwijnen** [mrichar1/jsonapi-vuex#85]
Is there a recommended way to get the relationship resources of a certain parent resource? They can be fetched from the server with the getRelated method, but I can't find if there is a getter to get the fetched relations from the store.
It can be done with jsonPath syntax, e.g.:
```
this.$store.getters['jv/get']('contactperson', '$[?(@._jv.relationships.customer.data.id=="' + this.customerId + '")]')
```
but this looks a bit rough for such a trivial task.

By the way, the jsonPath examples for filtering in the readme seem to be missing the '$' operator.

**Comment by mrichar1** [comment]
The `jsonPath` filter exists to filter a collection (or entire store) `get` so that it only contains matching items - so only returning parents that have a particular child relationship.

In your example above, this would return all `contactperson` items that had a particular related customer.

However your opening statement implies that what you want is to get (some of?) the relationships from a particular parent.

In this case the usual way would be to either look at the [relationships 'directly'](https://github.com/mrichar1/jsonapi-vuex#related-items)  in the root (as enabled by the default config option `followRelationshipsData`), or use the [helper function](https://github.com/mrichar1/jsonapi-vuex#helper-functions) `_jv.rels` to get all relationships from the parent object (using javascript filters etc if only a subset are required).

Let me know if this solves your issue, or if there's something I've missed!

**Comment by mrichar1** [comment]
(Have also fixed the missing `$` in the examples - thanks!)

**Comment by stefanvanherwijnen** [comment]
Thanks, I disabled `followRelationshipsData` because on post/patch the expanded relationships in `attributes` would be sent along as an empty array. This caused validation errors on my server. I realized that the relationships should just be defined as getters, which they already are (:+1: ), and then noticed that I copied the object with `JSON.parse(JSON.stringify())`...

So this works for retrieving the relationshp now:
```
const contactPeople = this.$store.getters['jv/get']('customer/' + this.customerId)._jv.rels.contactPeople
```

Thanks for the help :smile: . If I get everything working I might do a PR for a documentation update, as this package clearly offers much more than the docs reveal on first sight.

**Comment by mrichar1** [comment]
That's good to hear - glad you got it working!

Yes, the docs could do with restructuring - the project has grown very rapidly and the features are scattered throughout the docs, so a refactoring PR would be great!

**Comment by stefanvanherwijnen** [comment]
One more question regarding this issue: how would I update the relationships of e.g. a customer if a contactPerson relation is posted to the server? The post request returns the created contactPerson, but the relations of the customer aren't automatically updated.
The easiest solution is obviously querying the server for the new customer data, but I am not sure if this is recommended.

**Comment by mrichar1** [comment]
There are 2 ways this can be done in the JSONAPI spec, one of which currently works, and the other of which I've had an offline discussion about and expect an Issue to be opened soon.

1. Modify the `relationships` section in the 'parent' object - https://jsonapi.org/format/#crud-updating-resource-relationships

This approach is currently supported. If `cleanPatch` is `false` (the default), or if it is `true` and `cleanPatchProps` includes `relationships`, then any relationships in the object being passed to the `patch` action will be included in the PATCH to the api.

It sounds though that you aren't seeing this working as expected (though you mention PATCH when this is really done by a POST, so might be doing something different?) Can you open a new issue with details if this isn't working for you.

2. Make a special request to the `relationships` endpoint - https://jsonapi.org/format/#crud-updating-relationships

This is not (yet) supported in the module, but should be added soon (and will probably be the default way to modify relationships).

The reason for needing `2.` is that the contents of the relationship section of the JSON is 'definitive' and overwrites the entire relationship.  This means you need to send all the items in the relationship as part of the PATCH - which could result in race conditions, and makes partial relationship requests risky.

**Comment by stefanvanherwijnen** [comment]
Maybe I wasn't enterily clear. I use the `rels` object of a customer to retrieve the related contact people. When I want to add a contact person, I make a `POST` request to `/contactpeople`, with the customer in the `relationships` key.  This works, but the client is not aware that the customer has an added contact person. I think `2` would solve the problem and make it clear to both client and server that a relationship has been modified.

Thanks again, I'll keep an eye out for upcoming features.

**Comment by mrichar1** [comment]
Ah, I understand now. Yes, the `post` and `patch` actions don't seem to work through relationship resource links and replace them with getters in the store, which they probably should.

I'll move this into a new issue to remind me to look into fixing it - thanks!
